package com.kgc.exam.springbootdemo1.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goods
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Goods {
    /**
     * Database Column Remarks:
     *   商品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_id
     *
     * @mbg.generated
     */
    private Long gId;

    /**
     * Database Column Remarks:
     *   商品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_name
     *
     * @mbg.generated
     */
    private String gName;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_price
     *
     * @mbg.generated
     */
    private Double gPrice;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_content
     *
     * @mbg.generated
     */
    private String gContent;

    /**
     * Database Column Remarks:
     *   上传日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.uploadTime
     *
     * @mbg.generated
     */
    private Date uploadtime;

    /**
     * Database Column Remarks:
     *   折扣状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.countStatus
     *
     * @mbg.generated
     */
    private Integer countstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_id
     *
     * @return the value of goods.g_id
     *
     * @mbg.generated
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_id
     *
     * @param gId the value for goods.g_id
     *
     * @mbg.generated
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_name
     *
     * @return the value of goods.g_name
     *
     * @mbg.generated
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_name
     *
     * @param gName the value for goods.g_name
     *
     * @mbg.generated
     */
    public void setgName(String gName) {
        this.gName = gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_price
     *
     * @return the value of goods.g_price
     *
     * @mbg.generated
     */
    public Double getgPrice() {
        return gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_price
     *
     * @param gPrice the value for goods.g_price
     *
     * @mbg.generated
     */
    public void setgPrice(Double gPrice) {
        this.gPrice = gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_content
     *
     * @return the value of goods.g_content
     *
     * @mbg.generated
     */
    public String getgContent() {
        return gContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_content
     *
     * @param gContent the value for goods.g_content
     *
     * @mbg.generated
     */
    public void setgContent(String gContent) {
        this.gContent = gContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.uploadTime
     *
     * @return the value of goods.uploadTime
     *
     * @mbg.generated
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.uploadTime
     *
     * @param uploadtime the value for goods.uploadTime
     *
     * @mbg.generated
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.countStatus
     *
     * @return the value of goods.countStatus
     *
     * @mbg.generated
     */
    public Integer getCountstatus() {
        return countstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.countStatus
     *
     * @param countstatus the value for goods.countStatus
     *
     * @mbg.generated
     */
    public void setCountstatus(Integer countstatus) {
        this.countstatus = countstatus;
    }
}