package com.kgc.exam.springbootdemo1.dto;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TestUser {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.u_id
     *
     * @mbg.generated
     */
    private Long uId;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.u_phonne_number
     *
     * @mbg.generated
     */
    private String uPhonneNumber;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.u_nickname
     *
     * @mbg.generated
     */
    private String uNickname;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.u_sex
     *
     * @mbg.generated
     */
    private Integer uSex;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.u_password
     *
     * @mbg.generated
     */
    @NotNull
    private String uPassword;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.u_creaed_time
     *
     * @mbg.generated
     */
    private Date uCreaedTime;

    /**
     * Database Column Remarks:
     *   积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.u_score
     *
     * @mbg.generated
     */
    private Long uScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.u_id
     *
     * @return the value of test_user.u_id
     *
     * @mbg.generated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.u_id
     *
     * @param uId the value for test_user.u_id
     *
     * @mbg.generated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.u_phonne_number
     *
     * @return the value of test_user.u_phonne_number
     *
     * @mbg.generated
     */
    public String getuPhonneNumber() {
        return uPhonneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.u_phonne_number
     *
     * @param uPhonneNumber the value for test_user.u_phonne_number
     *
     * @mbg.generated
     */
    public void setuPhonneNumber(String uPhonneNumber) {
        this.uPhonneNumber = uPhonneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.u_nickname
     *
     * @return the value of test_user.u_nickname
     *
     * @mbg.generated
     */
    public String getuNickname() {
        return uNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.u_nickname
     *
     * @param uNickname the value for test_user.u_nickname
     *
     * @mbg.generated
     */
    public void setuNickname(String uNickname) {
        this.uNickname = uNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.u_sex
     *
     * @return the value of test_user.u_sex
     *
     * @mbg.generated
     */
    public Integer getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.u_sex
     *
     * @param uSex the value for test_user.u_sex
     *
     * @mbg.generated
     */
    public void setuSex(Integer uSex) {
        this.uSex = uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.u_password
     *
     * @return the value of test_user.u_password
     *
     * @mbg.generated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.u_password
     *
     * @param uPassword the value for test_user.u_password
     *
     * @mbg.generated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.u_creaed_time
     *
     * @return the value of test_user.u_creaed_time
     *
     * @mbg.generated
     */
    public Date getuCreaedTime() {
        return uCreaedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.u_creaed_time
     *
     * @param uCreaedTime the value for test_user.u_creaed_time
     *
     * @mbg.generated
     */
    public void setuCreaedTime(Date uCreaedTime) {
        this.uCreaedTime = uCreaedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.u_score
     *
     * @return the value of test_user.u_score
     *
     * @mbg.generated
     */
    public Long getuScore() {
        return uScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.u_score
     *
     * @param uScore the value for test_user.u_score
     *
     * @mbg.generated
     */
    public void setuScore(Long uScore) {
        this.uScore = uScore;
    }
}