package com.kgc.exam.springbootdemo1.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public TestUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUIdIsNull() {
            addCriterion("u_id is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("u_id is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(Long value) {
            addCriterion("u_id =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(Long value) {
            addCriterion("u_id <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(Long value) {
            addCriterion("u_id >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(Long value) {
            addCriterion("u_id >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(Long value) {
            addCriterion("u_id <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(Long value) {
            addCriterion("u_id <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<Long> values) {
            addCriterion("u_id in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<Long> values) {
            addCriterion("u_id not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(Long value1, Long value2) {
            addCriterion("u_id between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(Long value1, Long value2) {
            addCriterion("u_id not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberIsNull() {
            addCriterion("u_phonne_number is null");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberIsNotNull() {
            addCriterion("u_phonne_number is not null");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberEqualTo(String value) {
            addCriterion("u_phonne_number =", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberNotEqualTo(String value) {
            addCriterion("u_phonne_number <>", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberGreaterThan(String value) {
            addCriterion("u_phonne_number >", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("u_phonne_number >=", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberLessThan(String value) {
            addCriterion("u_phonne_number <", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberLessThanOrEqualTo(String value) {
            addCriterion("u_phonne_number <=", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberLike(String value) {
            addCriterion("u_phonne_number like", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberNotLike(String value) {
            addCriterion("u_phonne_number not like", value, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberIn(List<String> values) {
            addCriterion("u_phonne_number in", values, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberNotIn(List<String> values) {
            addCriterion("u_phonne_number not in", values, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberBetween(String value1, String value2) {
            addCriterion("u_phonne_number between", value1, value2, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUPhonneNumberNotBetween(String value1, String value2) {
            addCriterion("u_phonne_number not between", value1, value2, "uPhonneNumber");
            return (Criteria) this;
        }

        public Criteria andUNicknameIsNull() {
            addCriterion("u_nickname is null");
            return (Criteria) this;
        }

        public Criteria andUNicknameIsNotNull() {
            addCriterion("u_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andUNicknameEqualTo(String value) {
            addCriterion("u_nickname =", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotEqualTo(String value) {
            addCriterion("u_nickname <>", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameGreaterThan(String value) {
            addCriterion("u_nickname >", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("u_nickname >=", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLessThan(String value) {
            addCriterion("u_nickname <", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLessThanOrEqualTo(String value) {
            addCriterion("u_nickname <=", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLike(String value) {
            addCriterion("u_nickname like", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotLike(String value) {
            addCriterion("u_nickname not like", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameIn(List<String> values) {
            addCriterion("u_nickname in", values, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotIn(List<String> values) {
            addCriterion("u_nickname not in", values, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameBetween(String value1, String value2) {
            addCriterion("u_nickname between", value1, value2, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotBetween(String value1, String value2) {
            addCriterion("u_nickname not between", value1, value2, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUSexIsNull() {
            addCriterion("u_sex is null");
            return (Criteria) this;
        }

        public Criteria andUSexIsNotNull() {
            addCriterion("u_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUSexEqualTo(Integer value) {
            addCriterion("u_sex =", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotEqualTo(Integer value) {
            addCriterion("u_sex <>", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexGreaterThan(Integer value) {
            addCriterion("u_sex >", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_sex >=", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexLessThan(Integer value) {
            addCriterion("u_sex <", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexLessThanOrEqualTo(Integer value) {
            addCriterion("u_sex <=", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexIn(List<Integer> values) {
            addCriterion("u_sex in", values, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotIn(List<Integer> values) {
            addCriterion("u_sex not in", values, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexBetween(Integer value1, Integer value2) {
            addCriterion("u_sex between", value1, value2, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotBetween(Integer value1, Integer value2) {
            addCriterion("u_sex not between", value1, value2, "uSex");
            return (Criteria) this;
        }

        public Criteria andUPasswordIsNull() {
            addCriterion("u_password is null");
            return (Criteria) this;
        }

        public Criteria andUPasswordIsNotNull() {
            addCriterion("u_password is not null");
            return (Criteria) this;
        }

        public Criteria andUPasswordEqualTo(String value) {
            addCriterion("u_password =", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotEqualTo(String value) {
            addCriterion("u_password <>", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordGreaterThan(String value) {
            addCriterion("u_password >", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("u_password >=", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLessThan(String value) {
            addCriterion("u_password <", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLessThanOrEqualTo(String value) {
            addCriterion("u_password <=", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLike(String value) {
            addCriterion("u_password like", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotLike(String value) {
            addCriterion("u_password not like", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordIn(List<String> values) {
            addCriterion("u_password in", values, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotIn(List<String> values) {
            addCriterion("u_password not in", values, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordBetween(String value1, String value2) {
            addCriterion("u_password between", value1, value2, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotBetween(String value1, String value2) {
            addCriterion("u_password not between", value1, value2, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeIsNull() {
            addCriterion("u_creaed_time is null");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeIsNotNull() {
            addCriterion("u_creaed_time is not null");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeEqualTo(Date value) {
            addCriterion("u_creaed_time =", value, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeNotEqualTo(Date value) {
            addCriterion("u_creaed_time <>", value, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeGreaterThan(Date value) {
            addCriterion("u_creaed_time >", value, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("u_creaed_time >=", value, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeLessThan(Date value) {
            addCriterion("u_creaed_time <", value, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeLessThanOrEqualTo(Date value) {
            addCriterion("u_creaed_time <=", value, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeIn(List<Date> values) {
            addCriterion("u_creaed_time in", values, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeNotIn(List<Date> values) {
            addCriterion("u_creaed_time not in", values, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeBetween(Date value1, Date value2) {
            addCriterion("u_creaed_time between", value1, value2, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUCreaedTimeNotBetween(Date value1, Date value2) {
            addCriterion("u_creaed_time not between", value1, value2, "uCreaedTime");
            return (Criteria) this;
        }

        public Criteria andUScoreIsNull() {
            addCriterion("u_score is null");
            return (Criteria) this;
        }

        public Criteria andUScoreIsNotNull() {
            addCriterion("u_score is not null");
            return (Criteria) this;
        }

        public Criteria andUScoreEqualTo(Long value) {
            addCriterion("u_score =", value, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreNotEqualTo(Long value) {
            addCriterion("u_score <>", value, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreGreaterThan(Long value) {
            addCriterion("u_score >", value, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreGreaterThanOrEqualTo(Long value) {
            addCriterion("u_score >=", value, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreLessThan(Long value) {
            addCriterion("u_score <", value, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreLessThanOrEqualTo(Long value) {
            addCriterion("u_score <=", value, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreIn(List<Long> values) {
            addCriterion("u_score in", values, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreNotIn(List<Long> values) {
            addCriterion("u_score not in", values, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreBetween(Long value1, Long value2) {
            addCriterion("u_score between", value1, value2, "uScore");
            return (Criteria) this;
        }

        public Criteria andUScoreNotBetween(Long value1, Long value2) {
            addCriterion("u_score not between", value1, value2, "uScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}