package com.kgc.exam.springbootdemo1.mapper;

import com.kgc.exam.springbootdemo1.dto.WxPhone;
import com.kgc.exam.springbootdemo1.dto.WxPhoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    long countByExample(WxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int deleteByExample(WxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long wxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int insert(WxPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int insertSelective(WxPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    List<WxPhone> selectByExample(WxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    WxPhone selectByPrimaryKey(Long wxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxPhone record, @Param("example") WxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxPhone record, @Param("example") WxPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxPhone record);
}